### ISSUE TITLE
Inference Weights and codes

### ISSUE THREAD

**Issue by shubhaminnani** [CityU-AIM-Group/MultiModal-learning#1]
Hi @hathawayxxh ,
The research work is very interesting and want to infer the results. 

Did you plan to Release the weights and the codes. It will be exciting to see the results.

Thanks!

**Comment by hathawayxxh** [comment]
Thanks for your interest in our work. Currently, this work is extended and submitted to MIA. Since there is some overlap between the codes of the conference and journal versions, we will release the codes after the journal paper is accepted.
